pipeline {
    agent any

    environment {
        IMAGE = "anishs14/devops-app"
        SONAR_ENV = "sonar"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Anish-Narayan/devops-project.git'
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'python:3.11'
                }
            }
            steps {
                sh 'python -m py_compile app/app.py'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv(SONAR_ENV) {
                    sh 'sonar-scanner'
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE:$BUILD_NUMBER -f docker/Dockerfile .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $IMAGE:$BUILD_NUMBER
                    '''
                }
            }
        }

        stage('Update K8s Manifest') {
            steps {
                sh '''
                sed -i "s|image:.*|image: $IMAGE:$BUILD_NUMBER|" k8s/base/deployment.yaml
                git config user.name "jenkins"
                git config user.email "jenkins@example.com"
                git add k8s/base/deployment.yaml
                git commit -m "Update image to $BUILD_NUMBER"
                git push origin main
                '''
            }
        }
    }
}