pipeline {
    agent any

    environment {
        IMAGE = "anishs14/devops-app"
        SONAR_ENV = "sonar"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Anish-Narayan/devops-project.git'
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'python:3.11'
                }
            }
            steps {
                sh 'python -m py_compile app/app.py'
            }
        }
stage('SonarQube Analysis') {
    steps {
        script {
            docker.image('sonarsource/sonar-scanner-cli:latest')
                  .inside('--network devops-net') {
                withSonarQubeEnv('sonar') {
                    withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                        sh '''
                        sonar-scanner \
                          -Dsonar.login=$SONAR_TOKEN
                        '''
                    }
                }
            }
        }
    }
}

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE:$BUILD_NUMBER -f docker/Dockerfile .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $IMAGE:$BUILD_NUMBER
                    '''
                }
            }
        }

        stage('Update K8s Manifest') {
    steps {
        withCredentials([usernamePassword(
            credentialsId: 'github-creds',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_PASS'
        )]) {
            sh '''
            sed -i "s|image:.*|image: anishs14/devops-app:${BUILD_NUMBER}|" k8s/base/deployment.yaml

            git config user.name "jenkins"
            git config user.email "jenkins@example.com"

            git add k8s/base/deployment.yaml
            git commit -m "Update image to ${BUILD_NUMBER}"

            git push https://$GIT_USER:$GIT_PASS@github.com/Anish-Narayan/devops-project.git main
            '''
        }
    }
}
    }
}